# Generated by Django 2.2 on 2019-12-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191223_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='active',
        ),
        migrations.AddField(
            model_name='like',
            name='article_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
