# Generated by Django 2.2 on 2019-12-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191223_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='count',
            field=models.PositiveIntegerField(),
        ),
    ]
