# Generated by Django 2.2 on 2020-01-09 18:47

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('Monkey', 'Monkey'), ('Badger', 'Badger'), ('Bear', 'Bear')], max_length=60)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=2)),
                ('age', models.PositiveIntegerField()),
                ('nickname', models.CharField(max_length=120)),
                ('arrival_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson38.Animal')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson38.Visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)])),
                ('expiration_date', models.DateField()),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lesson38.Visitor')),
            ],
        ),
    ]
